// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3B15YP-pDwfmd9PSybCn4fiWdfHVOu2s',
    appId: '1:165641364532:web:0cd2038c0a6e937ecc9661',
    messagingSenderId: '165641364532',
    projectId: 'flutter-chat-app-62cea',
    authDomain: 'flutter-chat-app-62cea.firebaseapp.com',
    storageBucket: 'flutter-chat-app-62cea.appspot.com',
    measurementId: 'G-0KB0E62BS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtVo58e3W-kd0AcfZjo6B7HmQ7JwT2r9g',
    appId: '1:165641364532:android:91c25034d9827779cc9661',
    messagingSenderId: '165641364532',
    projectId: 'flutter-chat-app-62cea',
    storageBucket: 'flutter-chat-app-62cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkmYbBB-iyQAR-0sGCSoLHvi2DBQV6UBM',
    appId: '1:165641364532:ios:89981ba0afdeac79cc9661',
    messagingSenderId: '165641364532',
    projectId: 'flutter-chat-app-62cea',
    storageBucket: 'flutter-chat-app-62cea.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkmYbBB-iyQAR-0sGCSoLHvi2DBQV6UBM',
    appId: '1:165641364532:ios:dc26288443207508cc9661',
    messagingSenderId: '165641364532',
    projectId: 'flutter-chat-app-62cea',
    storageBucket: 'flutter-chat-app-62cea.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
